name: burhan_trial
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0" # Use a compatible SDK range

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.2.0
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  unity_ads_plugin: ^0.3.21


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/hd-wall.png"
  remove_alpha_ios: true # Change to your icon's path
