# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network statistics synchronously affecting flutter build times.
# To disable this, add this line to your Podfile:
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Add the Firebase pod for Crashlytics
# pod 'Firebase/Crashlytics'

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'Firebase/Firestore'
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseAnalytics', :modular_headers => true
  pod 'FirebaseFirestore', :modular_headers => true
  pod 'Google-Mobile-Ads-SDK', '>= 9.0.0'
  pod 'UnityAds', '~> 0.3.21'
  # Ensure Flutter dependencies are loaded
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
