# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'  # Change this to the desired minimum iOS version

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
# Disable these analytics by passing `--no-analytics` to `pod install`.
# You can also set the environment variable `COCOAPODS_DISABLE_STATS` to `true`.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Ensure Flutter dependencies are loaded
use_frameworks!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
