# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting performance.
# To disable this, add the following line to your `Podfile`:
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# The name of the target is typically your project name
target 'Runner' do
  # Comment the next line if you're not using Swift
  use_frameworks!

  # Pods for Runner
  # Add your pods here, e.g.:
  # pod 'Firebase/Analytics'

  # Ensure Flutter dependencies are loaded
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
